[package]
name = "winit_keyboard_tester"
version = "0.1.0"
edition = "2018"

[dependencies]
simple_logger = "1.11.0"
glow = "0.8.1"
glutin = "0.26.0"
winit = { path = "../winit" }
takeable-option = "0.4"

[target.'cfg(not(target_arc = "wasm32"))'.dependencies]
simple_logger = "1.11.0"

[target.'cfg(target_arc = "wasm32")'.dependencies]
web-sys = "0.3.49"

[patch.crates-io]
winit = { path = "../winit" }
